---
version: "2"
exclude_patterns:
  - "cache-templates/"
  - "tests/"
  - "templates/"
  - "genTravis.php"
plugins:
  duplication:
    enabled: true
    config:
      languages:
        - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      CleanCode/BooleanArgumentFlag:
        enabled: false
      CleanCode/StaticAccess:
        enabled: false
      UnusedFormalParameter:
        enabled: false
      Design/TooManyPublicMethods:
        enabled: false
  phpcodesniffer:
    enabled: true
  sonar-php:
    enabled: true
  phan:
    enabled: true
