---
engines:
  duplication:
    enabled: true
    exclude_paths:
    - "tests/"
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.php"
