name: Coverage

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        php: ['8.2']

    name: PHP ${{ matrix.php }} - ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer:v2
        coverage: xdebug

    - name: Install dependencies
      run: composer update --prefer-dist --no-progress --no-suggest --prefer-stable ${{ matrix.php >= 8 && '--ignore-platform-req=php' || '' }};

    - name: Run test suite
      run: vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.xml

    - name: Code Climate Test Reporter
      uses: aktions/codeclimate-test-reporter@v1
      with:
        codeclimate-test-reporter-id: ${{ secrets.CC_TEST_REPORTER_ID }}
        command: after-build -t clover
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      continue-on-error: true

    - name: Coverage
      uses: codecov/codecov-action@v3
      with:
       token: ${{ secrets.CODECOV_TOKEN }}
